### ISSUE TITLE
DB: Update filename location

### ISSUE THREAD

**Issue by DeviousFusion** [UTA-FabLab/fabapp#57] opened 2020-09-21 17:19 UTC
Filenames are currently being stored in mats_used table. Move this back to transactions table. Possibly helps with #9

**Comment by FabosaurusRex** [comment] 2020-09-21 18:09
Needs to be fixed and ready for testing by Oct. 12.

**Comment by FabosaurusRex** [comment] 2020-10-08 19:45
This appears to be the root cause of #9.

**Comment by FabosaurusRex** [comment] 2020-10-08 22:33
Filename location has been updated to the Transactions notes field from the mats_used notes field.  Closing.

**Closed as completed by FabosaurusRex** 2020-10-08 22:33 UTC
Labels: Bug, Medium Priority Bug
